name: Generate SBOM with CycloneDX for PHP 8.0

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    name: PHP 8.0 SBOM Generation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          tools: composer

      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: composer update --prefer-lowest --no-progress --no-scripts

      - name: Allow Composer Plugin
        run: composer config --no-plugins allow-plugins.cyclonedx/cyclonedx-php-composer true

      - name: Install CycloneDX-Composer
        run: |
          composer require --dev cyclonedx/cyclonedx-php-composer
          composer install --no-progress --no-scripts

      - name: Verify CycloneDX Installation
        run: |
          composer show cyclonedx/cyclonedx-php-composer
          if ! composer CycloneDX:make-sbom composer.json --help > /dev/null 2>&1; then
            echo "❌ CycloneDX command not found! Exiting..."
            exit 1
          fi

      - name: Generate SBOM (JSON and XML)
        run: |
          composer CycloneDX:make-sbom composer.json --output-file sbom.json
          composer CycloneDX:make-sbom composer.json --output-format xml --output-file sbom.xml

      - name: Configure Git for Pushing to Another Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Clone the Target Repository
        run: |
          git clone https://oauth2:${{ secrets.SEU_PERSONAL_ACCESS_TOKEN }}@github.com/GT-SEG-FITBANK/SBOM.git target-repo
          cp sbom.json sbom.xml target-repo/
          cd target-repo
          git checkout -b sbom-update || git checkout sbom-update
          git add sbom.json sbom.xml
          git commit -m "Update SBOM for PHP 8.0 [Automated]"
          git push https://oauth2:${{ secrets.SEU_PERSONAL_ACCESS_TOKEN }}@github.com/GT-SEG-FITBANK/SBOM.git sbom-update
        
